FROM mcr.microsoft.com/devcontainers/base:debian

RUN apt update --assume-yes && \
    apt-get install --assume-yes --no-install-recommends \
        cpio \
        debian-archive-keyring \
        debian-keyring \
        debootstrap \
        e2fsprogs \
        systemd-repart \
        systemd-ukify \
        zstd

RUN mkdir /opt/mkosi && \
    git clone https://github.com/systemd/mkosi.git --revision=d6ddc66acb05d3d761d3f600c6b029319db9ae95 /opt/mkosi && \
    ln -s /opt/mkosi/bin/mkosi /usr/bin/mkosi